networks:
  ai_agents_network:
    driver: bridge
services:
  mary:
    build: ./Mary2ish
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 30s
      test:
      - CMD
      - curl
      - -f
      - http://localhost:8501/_stcore/health
      timeout: 10s
    ports:
    - "8004:8501"
    networks:
    - ai_agents_network
    volumes:
    - ./configs/mary/fastagent.config.yaml:/app/fastagent.config.yaml
    - ./configs/mary/ui.config.yaml:/app/ui.config.yaml
    - ./configs/mary/system_prompt.txt:/app/system_prompt.txt
    - ./configs/mary/knowledge_facts.txt:/app/knowledge_facts.txt
    - ./configs/mary/fastagent.secrets.yaml:/app/fastagent.secrets.yaml
  rick:
    build: ./Mary2ish
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 30s
      test:
      - CMD
      - curl
      - -f
      - http://localhost:8501/_stcore/health
      timeout: 10s
    ports:
    - "8005:8501"
    networks:
    - ai_agents_network
    volumes:
    - ./configs/rick/fastagent.config.yaml:/app/fastagent.config.yaml
    - ./configs/rick/ui.config.yaml:/app/ui.config.yaml
    - ./configs/rick/system_prompt.txt:/app/system_prompt.txt
    - ./configs/rick/knowledge_facts.txt:/app/knowledge_facts.txt
    - ./configs/rick/fastagent.secrets.yaml:/app/fastagent.secrets.yaml
