[project]
name = "fast-agent-testing"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "asyncio>=3.4.3",
    "fast-agent-mcp>=0.2.36",
    "ipykernel>=6.29.5",
]
